//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoofuserplans.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int Client_id { get; set; }
        [Required(ErrorMessage = "Please enter Phone no")]
        public string Phone_no { get; set; }
        [Required(ErrorMessage = "Please enter first name")]
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public Nullable<int> Current_plan { get; set; }
        public Nullable<decimal> Lastthree_m { get; set; }
        public Nullable<decimal> Lastsix_m { get; set; }
        public Nullable<decimal> Lastone_yr { get; set; }
        public string Typeof_user { get; set; }
        [Required(ErrorMessage = "Please enter date of birth")]
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> Plan_id { get; set; }
    }
}
